services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/expense_splitter
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      JWT_SECRET: ThisIsA256BitSecretKey_ChangeThisToYourOwnRandomLongKey123456
      JWT_EXPIRATION: 86400000
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_BASE_URL: http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: expense_splitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
